pipeline:
  build:
    when: 
      branch: master
      event: push
    image: plugins/docker
    dockerfile: Dockerfile
    settings:
      repo: pravinit2/drone-test
      tags: 
        - "build${DRONE_COMMIT:0:8}"
