pipeline:
  build:
    when: 
      branch: master
      event: push
    image: plugins/docker
    dockerfile: Dockerfile
    repo: pravinit2/drone-test
    secrets: [ docker_username, docker_password ]
    tags: [ "${DRONE_COMMIT_SHA:0:7}", latest ]
    
